on: push
name: CI

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        apt-get update -qqy
        apt-get install xvfb xserver-xephyr x11-utils
    - name: Go Test
      uses: cedrickring/golang-action@1.5.2
      env:
        GO111MODULE: "on"
